# Generated by Django 6.0.3 on 2026-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='companyname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='create_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ship_to_different_address',
            field=models.BooleanField(default=False),
        ),
    ]
